---
title: "NYC Restaurant Inspection: Exploring the Data"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Setup

```{r Setup}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      warning=FALSE, message=FALSE)
```

## Loading libraries 
```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(leaflet)
library(knitr)
```


## 1.  Pulling in the dataset
```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspect = 
  GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")
```

## 2.  Data wrangling, cleaning up the dataset.
```{r}
rest_inspect = rest_inspect %>% 
  filter(grade %in% c("A", "B", "C"), boro != "0")
```

## 3.  Exploring dataset

### Grades

#### Counting how many restaurants by grade, by type.

```{r}
rest_inspect %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  kable() 

rest_inspect %>% 
  count(boro, cuisine_description) %>% 
  kable()
```

#### Now considering different types of cuisine.

##### Italian/ Pizza Restaurants in NYC

```{r}
italian = c("Italian", "Italian/Pizza")

rest_inspect %>% 
  filter(str_detect(cuisine_description, italian)) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  kable()
```

##### French Restaurants in NYC

```{r}
rest_inspect %>% 
  filter(str_detect(cuisine_description, "French")) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  kable()
```

##### Mexican Restaurants in NYC
```{r}
rest_inspect %>% 
  filter(str_detect(cuisine_description, "Mexican")) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  kable()
```

##### Pan-Asian Restaurants in NYC

```{r}
asian = c("Asian", "Japanese", "Korean", "Chinese")

rest_inspect %>% 
  filter(str_detect(cuisine_description, asian)) %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, values_from = n) %>% 
  kable()
```